<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rov">

<!-- This is an .xacro file - that means it gets turned into a .urdf file 
     after a couple of commands. It's used to simulate the ROV with ROS. -->

  <!-- Some macros for making inertia definition easier-->
  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Xacro Properties Definition -->

  <!-- The following two properties are the 
       dimensions of the 15x15mm frame-->
  <xacro:property name="width" value = "0.37" />
  <xacro:property name="depth" value = "0.41" />
  <xacro:property name="height" value = "0.20" />
  <xacro:property name="extrusion_width" value = "0.015" />

  <!-- Materials definition -->
  <material name="silver">
    <color rgba="0.6 0.6 0.6 1"/>
  </material>
  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="beige">
    <color rgba="0.88 0.8 0.6 1"/>
  </material>
  <material name="red">
    <color rgba="0.9 0.1 0.1 1"/>
  </material>

  <!-- MEH -->

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.16 0.11 0.16"/>
      </geometry>
      <origin xyz="0 -0.055 0.04"/>
      <material name="beige"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.16 0.11 0.16"/>
      </geometry>
      <origin xyz="0 -0.055 0.04"/>
    </collision>
    <xacro:inertial_box mass="0.8" x="0.16" y="0.11" z="0.16">
      <origin xyz="0 -0.055 0.04" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <!-- Upper Frame Definition -->

  <link name="MEH_Crossbar">
    <visual>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${width * 0.34}" x="${width}" y="${extrusion_width}" z="${extrusion_width}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>
  
  <joint name="MEH_Crossbar_to_MEH" type="fixed">
    <parent link="base_link"/>
    <child link="MEH_Crossbar"/>
  </joint>

  <link name="Upper_Left_Crossbar">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </collision>
    <xacro:inertial_box mass="${depth * 0.34}" x="${extrusion_width}" y="${depth}" z="${extrusion_width}">
      <origin xyz="0 0.12 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="MEH_Crossbar_UL_Crossbar" type="fixed">
    <parent link="MEH_Crossbar"/>
    <child link="Upper_Left_Crossbar"/>
    <origin xyz="${-width / 2} 0 0"/>
  </joint>

  <link name="Upper_Right_Crossbar">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </collision>
    <xacro:inertial_box mass="${depth * 0.34}" x="${extrusion_width}" y="${depth}" z="${extrusion_width}">
      <origin xyz="0 0.12 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="MEH_Crossbar_UR_Crossbar" type="fixed">
    <parent link="MEH_Crossbar"/>
    <child link="Upper_Right_Crossbar"/>
    <origin xyz="${width / 2} 0 0"/>
  </joint>

  <link name="Upper_Back_Crossbar">
    <visual>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="${width / 2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="${width / 2} 0 0"/>
    </collision>
    <xacro:inertial_box mass="${width*0.34}" x="${width}" y="${extrusion_width}" z="${extrusion_width}">
      <origin xyz="${width / 2} 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="UB_Crossbar_UL_Crossbar" type="fixed">
    <parent link="Upper_Left_Crossbar"/>
    <child link="Upper_Back_Crossbar"/>
    <origin xyz="0 ${depth - 0.08} 0"/>
  </joint>

  <!-- Vertical Frame Definition -->

  <!-- Macros to quickly bang out the vertical posts-->
  <xacro:macro name="frame_post">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} ${height}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 0 -${height / 2}"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} ${height}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 0 -${height / 2}"/>
    </collision>
    <xacro:inertial_box mass="${height * 0.34}" x="${extrusion_width}" y="${extrusion_width}" z="${height}">
      <origin xyz="0 0 -${height / 2}"/>
    </xacro:inertial_box>
  </xacro:macro>

  <link name="Left_Post">
    <xacro:frame_post/>
  </link>

  <joint name="UL_Crossbar_Left_Post" type="fixed">
    <parent link="Upper_Left_Crossbar"/>
    <child link="Left_Post"/>
  </joint>

  <link name="Right_Post">
    <xacro:frame_post/>
  </link>

  <joint name="UR_Crossbar_Right_Post" type="fixed">
    <parent link="Upper_Right_Crossbar"/>
    <child link="Right_Post"/>
  </joint>

  <link name="Back_Left_Post">
    <xacro:frame_post/>
  </link>

  <joint name="UL_Crossbar_BL_Post" type="fixed">
    <parent link="Upper_Back_Crossbar"/>
    <child link="Back_Left_Post"/>
    <origin xyz="${width * 0.3} 0 0"/>
  </joint>

  <link name="Back_Right_Post">
    <xacro:frame_post/>
  </link>

  <joint name="UR_Crossbar_BR_Post" type="fixed">
    <parent link="Upper_Back_Crossbar"/>
    <child link="Back_Right_Post"/>
    <origin xyz="${width * 0.7} 0 0"/>
  </joint>

  <!-- Lower Frame Definition -->

  <link name="Lower_Front_Crossbar">
    <visual>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="${width / 2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="${width / 2} 0 0"/>
    </collision>
    <xacro:inertial_box mass="${width * 0.34}" x="${width}" y="${extrusion_width}" z="${extrusion_width}">
      <origin xyz="${width / 2} 0 0"/>
    </xacro:inertial_box>
  </link>
  
  <joint name="LF_Crossbar_Left_Post" type="fixed">
    <parent link="Left_Post"/>
    <child link="Lower_Front_Crossbar"/>
    <origin xyz="0 0 -${height}"/>
  </joint>

  <link name="Lower_Left_Crossbar">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </collision>
    <xacro:inertial_box mass="${depth*0.34}" x="${extrusion_width}" y="${depth}" z="${extrusion_width}">
      <origin xyz="0 0.12 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="LF_Crossbar_LL_Crossbar" type="fixed">
    <parent link="Lower_Front_Crossbar"/>
    <child link="Lower_Left_Crossbar"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="Lower_Right_Crossbar">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${depth} ${extrusion_width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0.12 0"/>
    </collision>
    <xacro:inertial_box mass="${depth*0.34}" x="${extrusion_width}" y="${depth}" z="${extrusion_width}">
      <origin xyz="0 0.12 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="LF_Crossbar_LR_Crossbar" type="fixed">
    <parent link="Lower_Front_Crossbar"/>
    <child link="Lower_Right_Crossbar"/>
    <origin xyz="${width} 0 0"/>
  </joint>

  <link name="Lower_Back_Crossbar">
    <visual>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="${width / 2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <origin xyz="${width / 2} 0 0"/>
    </collision>
    <xacro:inertial_box mass="${width*0.34}" x="${width}" y="${extrusion_width}" z="${extrusion_width}">
      <origin xyz="${width / 2} 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="LB_Crossbar_LL_Crossbar" type="fixed">
    <parent link="Lower_Left_Crossbar"/>
    <child link="Lower_Back_Crossbar"/>
    <origin xyz="0 ${depth - 0.08} 0"/>
  </joint>

  <!-- PSE and Static Buoyancy -->

  <link name="PSE">
    <visual>
      <geometry>
        <box size="0.17 0.12 0.055"/>
      </geometry>
      <material name="dark_gray"/>
      <origin xyz="0 -0.06 0.024"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.17 0.12 0.055"/>
      </geometry>
      <origin xyz="0 -0.06 0.024"/>
    </collision>
    <xacro:inertial_box mass="1" x="0.17" y="0.12" z="0.055">
      <origin xyz="0 -0.06 0.024" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="UB_Crossbar_PSE" type="fixed">
    <parent link="Upper_Back_Crossbar"/>
    <child link="PSE"/>
    <origin xyz="${width / 2} 0 0"/>
  </joint>

  <link name="SB_Left">
    <visual>
      <geometry>
        <cylinder length="0.2" radius="0.055"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 -0.045 -0.125"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.055"/>
      </geometry>
      <origin xyz="0 -0.045 -0.125"/>
    </collision>
    <xacro:inertial_cylinder mass="0.3" length="0.2" radius="0.055">
      <origin rpy="0 0 0" xyz="0 -0.045 -0.125"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="UB_Crossbar_SB_Left" type="fixed">
    <parent link="Upper_Back_Crossbar"/>
    <child link="SB_Left"/>
    <origin rpy="4.71 0 0" xyz="${width * 0.1} 0 0"/>
  </joint>

  <link name="SB_Right">
    <visual>
      <geometry>
        <cylinder length="0.2" radius="0.055"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 -0.045 -0.125"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.055"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 -0.045 -0.125"/>
    </collision>
    <xacro:inertial_cylinder mass="0.3" length="0.2" radius="0.055">
      <origin rpy="0 0 0" xyz="0 -0.045 -0.125"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="UB_Crossbar_SB_Right" type="fixed">
    <parent link="Upper_Back_Crossbar"/>
    <child link="SB_Right"/>
    <origin rpy="4.71 0 0" xyz="${width * 0.9} 0 0"/>
  </joint>

  <!-- Thrusters -->

  <!-- Macros to quickly bang out the identical thrusters-->
  <xacro:macro name="horizontal_thruster">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <material name="black"/>
      <origin rpy="1.57 0 0.77" xyz="0 0 -0.045"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <material name="black"/>
      <origin rpy="1.57 0 0.77" xyz="0 0 -0.045"/>
    </collision>
    <xacro:inertial_cylinder mass="0.3" length="0.05" radius="0.045">
      <origin rpy="1.57 0 0.77" xyz="0 0 -0.045"/>
    </xacro:inertial_cylinder>
  </xacro:macro>

  <link name="Thruster_Front_Left">
    <xacro:horizontal_thruster/>
  </link>

  <joint name="UL_Crossbar_TFL" type="fixed">
    <parent link="Upper_Left_Crossbar"/>
    <child link="Thruster_Front_Left"/>
    <origin xyz="0 -0.06 0"/>
  </joint>

  <link name="Thruster_Back_Left">
    <xacro:horizontal_thruster/>
  </link>

  <joint name="UL_Crossbar_TBL" type="fixed">
    <parent link="Upper_Left_Crossbar"/>
    <child link="Thruster_Back_Left"/>
    <origin xyz="0 ${depth - 0.08} 0"/>
  </joint>

  <link name="Thruster_Front_Right">
    <xacro:horizontal_thruster/>
  </link>

  <joint name="UR_Crossbar_TFR" type="fixed">
    <parent link="Upper_Right_Crossbar"/>
    <child link="Thruster_Front_Right"/>
    <origin xyz="0 -0.06 0"/>
  </joint>

  <link name="Thruster_Back_Right">
    <xacro:horizontal_thruster/>
  </link>

  <joint name="UR_Crossbar_TBR" type="fixed">
    <parent link="Upper_Right_Crossbar"/>
    <child link="Thruster_Back_Right"/>
    <origin xyz="0 ${depth - 0.08} 0"/>
  </joint>

  <link name="Thruster_Vert_Left">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0" xyz="-0.045 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.045 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.3" length="0.05" radius="0.045">
      <origin rpy="0 0 0" xyz="-0.045 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="UL_Crossbar_TVL" type="fixed">
    <parent link="Upper_Left_Crossbar"/>
    <child link="Thruster_Vert_Left"/>
    <origin xyz="0 0.13 0"/>
  </joint>

  <link name="Thruster_Vert_Right">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0" xyz="0.045 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.045"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.045 0 0"/>
    </collision>
    <xacro:inertial_cylinder mass="0.3" length="0.05" radius="0.045">
      <origin rpy="0 0 0" xyz="0.045 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="UL_Crossbar_TVR" type="fixed">
    <parent link="Upper_Right_Crossbar"/>
    <child link="Thruster_Vert_Right"/>
    <origin xyz="0 0.13 0"/>
  </joint>

  <!-- Grippers -->

  <link name="HGripper_Post">
    <visual>
      <geometry>
        <box size="${extrusion_width} 0.12 ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin xyz="0 -0.075 -0.125"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} 0.12 ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 -0.075 -0.125"/>
    </collision>
    <xacro:inertial_box mass="${0.12 * 0.34}" x="${extrusion_width}" y="0.12" z="${extrusion_width}">
      <origin rpy="0 0 0" xyz="0 -0.075 -0.125"/>
    </xacro:inertial_box>
  </link>

  <joint name="MEH_Crossbar_HGripper_Post" type="fixed">
    <parent link="MEH_Crossbar"/>
    <child link="HGripper_Post"/>
    <origin xyz="${width * 0.25} 0 0"/>
  </joint>

  <link name="HGripper_Crossbar">
    <visual>
      <geometry>
        <box size="0.15 ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.15 ${extrusion_width} ${extrusion_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${0.15 * 0.34}" x="0.15" y="${extrusion_width}" z="${extrusion_width}">
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="HGripper_Post_HGripper_Crossbar" type="fixed">
    <parent link="HGripper_Post"/>
    <child link="HGripper_Crossbar"/>
    <origin xyz="0 -0.14 -0.125"/>
  </joint>

  <link name="HGripper_Finger_Static">
    <visual>
      <geometry>
        <box size="${extrusion_width} 0.1 ${extrusion_width}"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 -0.05 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} 0.1 ${extrusion_width}"/>
      </geometry>
      <origin xyz="0 -0.05 0"/>
    </collision>
    <xacro:inertial_box mass="${0.1 * 0.34}" x="${extrusion_width}" y="0.1" z="${extrusion_width}">
      <origin rpy="0 0 0" xyz="0 -0.05 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="HGripper_Crossbar_HGF_Static" type="fixed">
    <parent link="HGripper_Crossbar"/>
    <child link="HGripper_Finger_Static"/>
    <origin xyz="-0.075 0 0"/>
  </joint>

  <link name="HGripper_Finger_Mobile">
    <visual>
      <geometry>
        <box size="${extrusion_width} 0.1 ${extrusion_width}"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 -0.05 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} 0.1 ${extrusion_width}"/>
      </geometry>
      <origin xyz="0 -0.05 0"/>
    </collision>
    <xacro:inertial_box mass="${0.1 * 0.34}" x="${extrusion_width}" y="0.1" z="${extrusion_width}">
      <origin rpy="0 0 0" xyz="0 -0.05 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="Front_Gripper" type="prismatic">
    <parent link="HGripper_Crossbar"/>
    <child link="HGripper_Finger_Mobile"/>
    <origin xyz="0.075 0 0"/>
    <limit effort="1000.0" lower="-0.15" upper="0" velocity="0.5"/>
  </joint>

  <link name="VGripper_Post">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.12"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0 -0.06"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.12"/>
      </geometry>
      <material name="silver"/>
      <origin rpy="0 0 0" xyz="0 0 -0.06"/>
    </collision>
    <xacro:inertial_box mass="${0.1 * 0.34}" x="${extrusion_width}" y="${extrusion_width}" z="0.12">
      <origin rpy="0 0 0" xyz="0 0 -0.06"/>
    </xacro:inertial_box>
  </link>

  <joint name="PSE_VGripper_Post" type="fixed">
    <parent link="PSE"/>
    <child link="VGripper_Post"/>
    <origin xyz="0 -0.12 0.03"/>
  </joint>

  <link name="VGripper_Crossbar">
    <visual>
      <geometry>
        <box size="0.15 ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.15 ${extrusion_width} ${extrusion_width}"/>
      </geometry>
      <material name="silver"/>
    </collision>
    <xacro:inertial_box mass="${0.15 * 0.34}" x="0.15" y="${extrusion_width}" z="${extrusion_width}">
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="VGripper_Post_VGripper_Crossbar" type="fixed">
    <parent link="VGripper_Post"/>
    <child link="VGripper_Crossbar"/>
    <origin xyz="0 0 -0.12"/>
  </joint>

  <link name="VGripper_Finger_Static">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.1"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 -0.05"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.1"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 -0.05"/>
    </collision>
    <xacro:inertial_box mass="${0.1 * 0.34}" x="${extrusion_width}" y="${extrusion_width}" z="0.1">
      <origin rpy="0 0 0" xyz="0 0 -0.05"/>
    </xacro:inertial_box>
  </link>

  <joint name="VGripper_Crossbar_VGF_Static" type="fixed">
    <parent link="VGripper_Crossbar"/>
    <child link="VGripper_Finger_Static"/>
    <origin xyz="-0.075 0 0"/>
  </joint>

  <link name="VGripper_Finger_Mobile">
    <visual>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.1"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 -0.05"/>
    </visual>
    <collision>
      <geometry>
        <box size="${extrusion_width} ${extrusion_width} 0.1"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 -0.05"/>
    </collision>
    <xacro:inertial_box mass="${0.1 * 0.34}" x="${extrusion_width}" y="${extrusion_width}" z="0.1">
      <origin rpy="0 0 0" xyz="0 0 -0.05"/>
    </xacro:inertial_box>
  </link>

  <joint name="Bottom_Gripper" type="prismatic">
    <parent link="VGripper_Crossbar"/>
    <child link="VGripper_Finger_Mobile"/>
    <origin xyz="0.075 0 0"/>
    <limit effort="1000.0" lower="-0.15" upper="0" velocity="0.5"/>
  </joint>

</robot>